version: "3"
services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:6.8.21
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"

  postgres:
    container_name: postgress
    image: mdillon/postgis
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_NAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - .database/:/var/lib/postgresql/data

  django:
    container_name: elastic_drf_example_django
    build:
      context: .
      dockerfile: ./Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - postgres
      - elasticsearch
